import Head from "next/head";
import Main from "src/components/Main";
import PageLayout from "src/components/PageLayout";
import GlobalStyles from "src/styles/GlobalStyles";
import React, {useEffect, useState} from "react";
import {ThemeProvider} from "@emotion/react";
import {themeConfig, ThemeProps} from "src/styles/theme";
import {useCustomTheme} from "src/hooks/useCustomTheme";

export default function Home() {
  const {theme}: {theme: ThemeProps} = useCustomTheme(themeConfig);

  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
    return () => setMounted(false);
  }, []);

  return !mounted ? null : (
    <>
      <Head>
        <title>Learn Portuguese</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/portugal.svg" />
      </Head>
      <GlobalStyles />
      <ThemeProvider theme={theme}>
        <PageLayout>
          <Main />
        </PageLayout>
      </ThemeProvider>
    </>
  );
}
