import Head from "next/head";
import Main from "src/components/Main";
import Scoreboard from "src/components/Scoreboard";
import PageLayout from "src/components/PageLayout";
import GlobalStyles from "src/styles/GlobalStyles";
import React, {useEffect, useState} from "react";

export default function Home() {
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
    return () => setMounted(false);
  }, []);

  return !mounted ? null : (
    <>
      <Head>
        <title>Learn Portuguese</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/portugal.svg" />
      </Head>
      <GlobalStyles />
      <PageLayout>
        <Scoreboard />
        <Main></Main>
      </PageLayout>
    </>
  );
}
